# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Session-Attributes
version:      0.01
version_from: lib/POE/Session/Attributes.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    Class::Inspector:              0
    POE:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
